/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	chaos_v1 "chaos-operator/pkg/apis/chaos/v1"
	versioned "chaos-operator/pkg/client/clientset/versioned"
	internalinterfaces "chaos-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "chaos-operator/pkg/client/listers/chaos/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ChaosInformer provides access to a shared informer and lister for
// Chaoses.
type ChaosInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ChaosLister
}

type chaosInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewChaosInformer constructs a new informer for Chaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredChaosInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredChaosInformer constructs a new informer for Chaos type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredChaosInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VerfV1().Chaoses(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VerfV1().Chaoses(namespace).Watch(options)
			},
		},
		&chaos_v1.Chaos{},
		resyncPeriod,
		indexers,
	)
}

func (f *chaosInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredChaosInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *chaosInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&chaos_v1.Chaos{}, f.defaultInformer)
}

func (f *chaosInformer) Lister() v1.ChaosLister {
	return v1.NewChaosLister(f.Informer().GetIndexer())
}
