/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	chaos_v1 "operator/pkg/apis/chaos/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChaoses implements ChaosInterface
type FakeChaoses struct {
	Fake *FakeVerfV1
	ns   string
}

var chaosesResource = schema.GroupVersionResource{Group: "verf.io", Version: "v1", Resource: "chaoses"}

var chaosesKind = schema.GroupVersionKind{Group: "verf.io", Version: "v1", Kind: "Chaos"}

// Get takes name of the chaos, and returns the corresponding chaos object, and an error if there is any.
func (c *FakeChaoses) Get(name string, options v1.GetOptions) (result *chaos_v1.Chaos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chaosesResource, c.ns, name), &chaos_v1.Chaos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chaos_v1.Chaos), err
}

// List takes label and field selectors, and returns the list of Chaoses that match those selectors.
func (c *FakeChaoses) List(opts v1.ListOptions) (result *chaos_v1.ChaosList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chaosesResource, chaosesKind, c.ns, opts), &chaos_v1.ChaosList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &chaos_v1.ChaosList{}
	for _, item := range obj.(*chaos_v1.ChaosList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested chaoses.
func (c *FakeChaoses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chaosesResource, c.ns, opts))

}

// Create takes the representation of a chaos and creates it.  Returns the server's representation of the chaos, and an error, if there is any.
func (c *FakeChaoses) Create(chaos *chaos_v1.Chaos) (result *chaos_v1.Chaos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chaosesResource, c.ns, chaos), &chaos_v1.Chaos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chaos_v1.Chaos), err
}

// Update takes the representation of a chaos and updates it. Returns the server's representation of the chaos, and an error, if there is any.
func (c *FakeChaoses) Update(chaos *chaos_v1.Chaos) (result *chaos_v1.Chaos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chaosesResource, c.ns, chaos), &chaos_v1.Chaos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chaos_v1.Chaos), err
}

// Delete takes name of the chaos and deletes it. Returns an error if one occurs.
func (c *FakeChaoses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chaosesResource, c.ns, name), &chaos_v1.Chaos{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChaoses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chaosesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &chaos_v1.ChaosList{})
	return err
}

// Patch applies the patch and returns the patched chaos.
func (c *FakeChaoses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *chaos_v1.Chaos, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chaosesResource, c.ns, name, data, subresources...), &chaos_v1.Chaos{})

	if obj == nil {
		return nil, err
	}
	return obj.(*chaos_v1.Chaos), err
}
